### PR TITLE
Survey page 

### PR DESCRIPTION
**Pull request by mattdelsordo**
See issue #129

### CODE REVIEW

**Comment by mattdelsordo** [comment]
Hmm, not quite sure why those other commits got pulled into this, sorry about that guys, I'll try and sort it out.

**Comment by Zevez7** [comment]
Looks good. Your version of the frontend main is old. You need to pull the latest frontend main into your survey branch. Then fix any merge problem. Then push to frontend main.

**Comment by Zevez7** [comment]
Instead of keeping the "form" folder in the component folder. You should move it into the "SurveyPage" folder. I like to keep all relevant component of a page into it's main page folder.

**Comment by Zevez7** [comment]
change your jsx file to js. JSX file name isn't necessary and JS is fine.

**Comment by mattdelsordo** [comment]
I'm going to close this and re-open after I rework it for the wireframe

**Pull request closed without merging**
