### PR TITLE
Feature: Filter Completed Assignments

### PR DESCRIPTION
**Pull request by EfrainAD**
1. Inside the 'AssignmentUnit' component, I added a showOnlyIncomplete useState, created a function to toggle the boolean value, and passed both the state and the toggle function to the 'OptionMenu' component.
2. I implemented a ternary operator to control whether a 'home' should be displayed. This decision is based on whether showOnlyIncomplete is set to true and whether home.complete is also true.
3. In the 'OptionMenu.js' file, I integrated a button that displayes differently based on whether showOnlyIncomplete is set to true or false. When clicked, it toggles the boolean value.
4. To maintain consistency with the rest of the site, I deconstructed the props that were passed into the OptionMenu component."

### CODE REVIEW

**Comment by EfrainAD** [comment]
Can I merge this in?

**Review by mattdelsordo — APPROVED** [review]
Strictly speaking I don't think this resolves https://github.com/codeforboston/urban-league-heat-pump-accelerator/issues/471, but it's a fine change and you can go ahead and merge it.

**Comment by EfrainAD** [comment]
I don't recall linking. It's a very small part. I have another PR that should though. I have comment on that PR. This one was a misread and you said it might be useful to the app users. So I added since I created it. 

> Strictly speaking I don't think this resolves https://github.com/codeforboston/urban-league-heat-pump-accelerator/issues/471, but it's a fine change and you can go ahead and merge it. Sorry for getting to this late.

**Comment by mattdelsordo** [comment]
You had #471 in the branch name so I made an assumption :grimacing:

**Comment by EfrainAD** [comment]
> You had #471 in the branch name so I made an assumption :grimacing: 

My bad. I thought it was when I made it. It is where I thought I was completing a small part. 

I changed my mind. It's part of it. It just shouldn't close it since there/was another PR that the main thing.

**Pull request merged**
